### ISSUE TITLE
Está sendo feito requisições desnecessária em telas que não são utilizadas

### ISSUE THREAD

**Issue by isaqueveras** [PedroMiguel7/API_BRISA_REACT#2]
Acredito eu que a requisição `/projetos` que pelo que analisei busca os projetos e é utilizado em outra página e não na pagina da imagem abaixo.

![image](https://user-images.githubusercontent.com/46972789/181131423-d8aa1078-8d8c-48e2-9f8d-2818668222c4.png)

## Requisições infinitas
Está sendo feito requisições infinitas nesta tela, verificar se tem algum for ou o components está sendo atualizado sem parar
Na imagem abaixo já ultrapassa +700 request no mesmo endpoint
![image](https://user-images.githubusercontent.com/46972789/181132020-a933aa85-66ef-4fe1-ab5e-053fe05a9482.png)

**Comment by PedroMiguel7** [comment]
Arrumei essas requisições repetidas. Vlw
